---
- name: Reconfigure nginx
  hosts: fabric
  gather_facts: no
  become: true
  become_user: "{{ elv_srv_username }}"
  roles:
    - eluvio-ansible-nginx
  vars:
    install_nginx: False
    setup_ssl: False
