---
- name: "Install or Update qfab {{ qfab_tgz }} and elvmasterd {{ elvmasterd_tgz }}"
  hosts: fabric
  gather_facts: no
  become: true
  become_user: "{{ elv_srv_username }}"
  serial: 1
  roles:
    - eluvio-ansible-elvmasterd-install
    - eluvio-ansible-fabric-install
