---
- name: "Install or Update qfab binaries and libs: {{ qfab_tgz }}"
  hosts: fabric
  gather_facts: no
  become: true
  become_user: "{{ elv_srv_username }}"
  serial: 1
  roles:
    - eluvio-ansible-fabric-install